development:
  adapter: postgresql

test:
  adapter: postgresql

production:
  adapter: postgresql



#development:
#  adapter: postgresql
#
#test:
#  adapter: postgresql
#
#production:
#  adapter: redis
#  url: redis://localhost:6379/1



#redis: &redis
#  adapter: redis
#  url: redis://localhost:6379/1
#
#production: *redis
#development: *redis
#test:
#  adapter: async
